/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package email;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class HomePageMail extends javax.swing.JFrame {

    /**
     * Creates new form homepageemail
     */
    String un;
    int check=0;//INBOX - SENT// 0-INBOX 1-SENT
    public void my_update(String str) {
	loggedin.setText(str);
        un=str;
        this.setTitle(str+" - Home");
        load_mail();
    }
    public HomePageMail() {
        initComponents();
        this.setLocationRelativeTo(null);
//        load_mail();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void load_mail(){
        check=0;
        String status;
        try {
          DefaultTableModel m = (DefaultTableModel) this.jTable1.getModel();
          m.setRowCount(0);
          JTableHeader th = jTable1.getTableHeader();
          TableColumnModel tcm = th.getColumnModel();
          TableColumn tc = tcm.getColumn(0);
          tc.setHeaderValue("SENDER");
          th.repaint();
          un=Encryption.encrpfun(loggedin.getText());
          Statement s =(Statement) Database.mycon().createStatement();
          ResultSet rs = s.executeQuery("Select * from email where receiver = '"+un+"' order by id desc;");
          while(rs.next()){
              status=Decryption.decrpfun(rs.getString("status"));
              m.addRow(new Object[] {
              Decryption.decrpfun(rs.getString("sender")),
              Decryption.decrpfun(rs.getString("content")),
              Decryption.decrpfun(rs.getString("date")),
              status
              });
          }
         s.close();
      } 
      catch (SQLException e) {
        System.out.println(e);  
      }
    }
    public void load_mail_sent(){
        check=1;
        String status="Sent";
        try {
          DefaultTableModel m = (DefaultTableModel) this.jTable1.getModel();
          m.setRowCount(0);
          JTableHeader th = jTable1.getTableHeader();
          TableColumnModel tcm = th.getColumnModel();
          TableColumn tc = tcm.getColumn(0);
          tc.setHeaderValue("RECEIVER");
          th.repaint();
          un=Encryption.encrpfun(loggedin.getText());
          Statement s =(Statement) Database.mycon().createStatement();
          ResultSet rs = s.executeQuery("Select * from email where sender='"+un+"' order by id desc;");
          while(rs.next()){
              m.addRow(new Object[] {
                  Decryption.decrpfun(rs.getString("receiver")),
                  Decryption.decrpfun(rs.getString("content")),
                  Decryption.decrpfun(rs.getString("date")),
                  status
              });
          }
          
         s.close();
      } 
      catch (SQLException e) {
        System.out.println(e);  
      }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reload = new javax.swing.JButton();
        inbox = new javax.swing.JButton();
        sent = new javax.swing.JButton();
        compose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loggedin = new javax.swing.JTextField();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(558, 440));

        reload.setText("RELOAD");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });

        inbox.setText("INBOX");
        inbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inboxActionPerformed(evt);
            }
        });

        sent.setText("SENT");
        sent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentActionPerformed(evt);
            }
        });

        compose.setText("COMPOSE");
        compose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                composeActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SENDER", "CONTENT", "DATE", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        loggedin.setEditable(false);
        loggedin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loggedinMouseClicked(evt);
            }
        });
        loggedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggedinActionPerformed(evt);
            }
        });

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loggedin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(compose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(sent, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reload)
                        .addGap(19, 19, 19)
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(loggedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(compose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        // TODO add your handling code here:
        load_mail();
    }//GEN-LAST:event_reloadActionPerformed

    private void inboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inboxActionPerformed
        // TODO add your handling code here:
        load_mail();
    }//GEN-LAST:event_inboxActionPerformed

    private void sentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentActionPerformed
        // TODO add your handling code here:
        load_mail_sent();
    }//GEN-LAST:event_sentActionPerformed

    private void composeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_composeActionPerformed
        // TODO add your handling code here:
        ComposeMail jf1 = new ComposeMail();
        jf1.my_update(loggedin.getText());
        jf1.setVisible(true);
        dispose();
    }//GEN-LAST:event_composeActionPerformed

    private void loggedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loggedinActionPerformed

    private void loggedinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loggedinMouseClicked
        // TODO add your handling code here:
        Profile jf1 = new Profile();
        jf1.my_update(loggedin.getText());
        jf1.setVisible(true);
        dispose();
    }//GEN-LAST:event_loggedinMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Home jf1 = new Home();
        jf1.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           int index = jTable1.getSelectedRow();
            TableModel model = jTable1.getModel();
            if(check==0){
            ExpandMail jf = new ExpandMail();
            String un=loggedin.getText();
            String sender = model.getValueAt(index, 0).toString();
            String content = model.getValueAt(index, 1).toString();
            String date = model.getValueAt(index, 2).toString();
            String statusv="Read";
            statusv=Encryption.encrpfun(statusv);
            un=Encryption.encrpfun(un);
            sender=Encryption.encrpfun(sender);
            content=Encryption.encrpfun(content);
            date=Encryption.encrpfun(date);
            try {
          Statement s =(Statement) Database.mycon().createStatement();
          ResultSet rs = s.executeQuery("Select * from email where sender='"+sender+"' and receiver = '"+un+"' and content='"+content+"' and date='"+date+"';");
          if(rs.next()){
              jf.maiload(
                      Decryption.decrpfun(un),
                      Decryption.decrpfun(sender),
                      Decryption.decrpfun(content), 
                      Decryption.decrpfun(date),
                      Decryption.decrpfun(rs.getString("subject"))
              );
              s.executeUpdate("Update email set status='"+statusv+"' where sender='"+sender+"' and receiver = '"+un+"' and content='"+content+"' and date='"+date+"';");
              jf.setVisible(true);
              dispose();
          }
         s.close();
      } 
      catch (SQLException e) {
        System.out.println(e);  
      }
            }
            else{
            ExpandMailSent jf = new ExpandMailSent();
            String un=loggedin.getText();
            String receiver = model.getValueAt(index, 0).toString();
            String content = model.getValueAt(index, 1).toString();
            String date = model.getValueAt(index, 2).toString();
            un=Encryption.encrpfun(un);
            receiver=Encryption.encrpfun(receiver);
            content=Encryption.encrpfun(content);
            date=Encryption.encrpfun(date);
            try {
          Statement s =(Statement) Database.mycon().createStatement();
          ResultSet rs = s.executeQuery("Select * from email where sender='"+un+"' and receiver = '"+receiver+"' and content='"+content+"' and date='"+date+"';");
          if(rs.next()){
              jf.maiload(
                      Decryption.decrpfun(un),
                      Decryption.decrpfun(receiver),
                      Decryption.decrpfun(content), 
                      Decryption.decrpfun(date),
                      Decryption.decrpfun(rs.getString("subject"))
              );
              jf.setVisible(true);
              dispose();
          }
         s.close();
      } 
      catch (SQLException e) {
        System.out.println(e);  
      }
            }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compose;
    private javax.swing.JButton inbox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField loggedin;
    private javax.swing.JButton logout;
    private javax.swing.JButton reload;
    private javax.swing.JButton sent;
    // End of variables declaration//GEN-END:variables
}
